# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLGeocoderTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'CLGeocoderTestsTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
